---
name: Build

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'
  schedule:
    - cron: "0 0 * * 3"

jobs:
  test_image:
    name: Test Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "[TEST] Build Image"
        run: docker build -t test-image .

      - name: "[TEST] Run Image"
        run: docker run --name test-image -d test-image sleep 120

      - name: "[TEST] Verify Image"
        run: docker exec --tty test-image --help

  release_image:
    name: Release
    runs-on: ubuntu-latest
    needs: test_image
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: yuriclopes/cvdupdate-alpine:latest